list: $/mcmraak/mcfaq/models/feedback/columns.yaml
modelClass: Mcmraak\Mcfaq\Models\Feedback
title: Feedback
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'mcmraak/mcfaq/feedback/update/:id'
